spring.application.name=atr
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/a_todo_resumen?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.sql.init.mode=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

path_cross=http://localhost:3000
path_mapping=api/v1

# JWT
jwt.secret=sTfHCRWRxxmVulf9B3XK6hmKoVvZRH8dBsOkcUJ11aQ=
jwt.expiration=86400000

# File upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB
file.upload-dir=uploads/resumenes
