INSERT IGNORE INTO areas (nombre, nivel, estado) VALUES
('Ingeniería en Sistemas de Información', 'GRADO', 'ACTIVA'),
('Ingeniería Química', 'GRADO', 'ACTIVA'),
('Ingeniería Electrónica', 'GRADO', 'ACTIVA'),
('Ingeniería Civil', 'GRADO', 'ACTIVA'),
('Ingeniería Mecánica', 'GRADO', 'ACTIVA'),
('Licenciatura en Administración Rural', 'GRADO', 'ACTIVA'),
('Licenciatura en Tecnología Educativa', 'GRADO', 'ACTIVA'),
('Tecnicatura en Programación', 'PREGRADO', 'ACTIVA'),
('Tecnicatura en Mecatrónica', 'PREGRADO', 'ACTIVA'),
('Tecnicatura en Logística', 'PREGRADO', 'ACTIVA'),
('Tecnicatura en Negociación de Bienes', 'PREGRADO', 'ACTIVA'),
('Tecnicatura en Material Rodante Ferroviario', 'PREGRADO', 'ACTIVA');

INSERT IGNORE INTO materias (nombre, area_id, anio, cuatrimestre, estado) VALUES
-- Area 1: Ingeniería en Sistemas de Información
('Análisis Matemático I', 1, 1, 1, 'ACTIVA'),
('Álgebra y Geometría Analítica', 1, 1, 1, 'ACTIVA'),
('Algoritmos y Estructuras de Datos', 1, 1, 1, 'ACTIVA'),
('Sistemas y Procesos de Negocios', 1, 1, 1, 'ACTIVA'),
('Física I', 1, 1, 2, 'ACTIVA'),
('Lógica y Estructuras Discretas', 1, 1, 2, 'ACTIVA'),
('Arquitectura de Computadoras', 1, 1, 2, 'ACTIVA'),
('Inglés I', 1, 1, 2, 'ACTIVA'),
('Análisis Matemático II', 1, 2, 1, 'ACTIVA'),
('Paradigmas de Programación', 1, 3, 1, 'ACTIVA'),
('Diseño de Sistemas', 1, 3, 1, 'ACTIVA'),
('Gestión de Datos', 1, 3, 2, 'ACTIVA'),
('Ingeniería de Software', 1, 3, 2, 'ACTIVA'),
('Redes de Información', 1, 4, 1, 'ACTIVA'),
('Sistemas Operativos', 1, 4, 1, 'ACTIVA'),
('Legislación', 1, 4, 2, 'ACTIVA'),
('Economía', 1, 4, 2, 'ACTIVA'),
('Inteligencia Artificial', 1, 5, 1, 'ACTIVA'),
('Administración de Recursos', 1, 5, 1, 'ACTIVA'),
('Simulación', 1, 5, 2, 'ACTIVA'),
('Proyecto Final', 1, 5, 2, 'ACTIVA'),

-- Area 2: Ingeniería Química
('Análisis Matemático I', 2, 1, 1, 'ACTIVA'),
('Álgebra', 2, 1, 1, 'ACTIVA'),
('Química General', 2, 1, 1, 'ACTIVA'),
('Física I', 2, 1, 2, 'ACTIVA'),
('Química Inorgánica', 2, 1, 2, 'ACTIVA'),
('Sistemas de Representación', 2, 1, 2, 'ACTIVA'),
('Análisis Matemático II', 2, 2, 1, 'ACTIVA'),
('Física II', 2, 2, 1, 'ACTIVA'),
('Química Orgánica I', 2, 2, 2, 'ACTIVA'),
('Ciencia de los Materiales', 2, 2, 2, 'ACTIVA'),
('Química Analítica', 2, 3, 1, 'ACTIVA'),
('Química Orgánica II', 2, 3, 1, 'ACTIVA'),
('Termodinámica', 2, 3, 2, 'ACTIVA'),
('Fenómenos de Transporte', 2, 3, 2, 'ACTIVA'),
('Operaciones Unitarias', 2, 4, 1, 'ACTIVA'),
('Reactores Químicos', 2, 4, 1, 'ACTIVA'),
('Microbiología Industrial', 2, 4, 2, 'ACTIVA'),
('Control de Procesos', 2, 5, 1, 'ACTIVA'),
('Diseño de Procesos', 2, 5, 1, 'ACTIVA'),
('Higiene y Seguridad Ambiental', 2, 5, 2, 'ACTIVA'),
('Evaluación de Proyectos', 2, 5, 2, 'ACTIVA'),
('Proyecto Final', 2, 5, 2, 'ACTIVA'),

-- Area 3: Ingeniería Electrónica
('Análisis Matemático I', 3, 1, 1, 'ACTIVA'),
('Álgebra', 3, 1, 1, 'ACTIVA'),
('Dispositivos Electrónicos', 3, 1, 1, 'ACTIVA'),
('Física I', 3, 1, 2, 'ACTIVA'),
('Informática I', 3, 1, 2, 'ACTIVA'),
('Análisis Matemático II', 3, 2, 1, 'ACTIVA'),
('Física II', 3, 2, 1, 'ACTIVA'),
('Circuitos Electrónicos I', 3, 2, 2, 'ACTIVA'),
('Técnicas Digitales I', 3, 2, 2, 'ACTIVA'),
('Circuitos Electrónicos II', 3, 3, 1, 'ACTIVA'),
('Técnicas Digitales II', 3, 3, 1, 'ACTIVA'),
('Señales y Sistemas', 3, 3, 2, 'ACTIVA'),
('Técnicas Digitales III', 3, 4, 1, 'ACTIVA'),
('Teoría de Circuitos', 3, 4, 1, 'ACTIVA'),
('Electrónica de Potencia', 3, 4, 2, 'ACTIVA'),
('Sistemas de Control', 3, 4, 2, 'ACTIVA'),
('Telecomunicaciones', 3, 5, 1, 'ACTIVA'),
('Higiene y Seguridad', 3, 5, 1, 'ACTIVA'),
('Legislación', 3, 5, 2, 'ACTIVA'),
('Proyectos Electrónicos', 3, 5, 2, 'ACTIVA'),
('Proyecto Final', 3, 5, 2, 'ACTIVA'),

-- Area 4: Ingeniería Civil
('Análisis Matemático I', 4, 1, 1, 'ACTIVA'),
('Álgebra', 4, 1, 1, 'ACTIVA'),
('Química General', 4, 1, 1, 'ACTIVA'),
('Ingeniería Civil I', 4, 1, 1, 'ACTIVA'),
('Física I', 4, 1, 2, 'ACTIVA'),
('Sistemas de Representación', 4, 1, 2, 'ACTIVA'),
('Fundamentos de Informática', 4, 1, 2, 'ACTIVA'),
('Análisis Matemático II', 4, 2, 1, 'ACTIVA'),
('Física II', 4, 2, 1, 'ACTIVA'),
('Probabilidad y Estadística', 4, 2, 1, 'ACTIVA'),
('Estabilidad', 4, 2, 2, 'ACTIVA'),
('Tecnología de los Materiales', 4, 2, 2, 'ACTIVA'),
('Ingeniería Civil II', 4, 2, 2, 'ACTIVA'),
('Resistencia de Materiales', 4, 3, 1, 'ACTIVA'),
('Tecnología del Hormigón', 4, 3, 1, 'ACTIVA'),
('Tecnología de la Construcción', 4, 3, 2, 'ACTIVA'),
('Geotopografía', 4, 4, 1, 'ACTIVA'),
('Hidráulica General', 4, 4, 1, 'ACTIVA'),
('Mecánica de Suelos', 4, 4, 2, 'ACTIVA'),
('Estructuras de Hormigón', 4, 4, 2, 'ACTIVA'),
('Vías de Comunicación', 4, 4, 2, 'ACTIVA'),
('Ingeniería Sanitaria', 4, 5, 1, 'ACTIVA'),
('Puentes', 4, 5, 1, 'ACTIVA'),
('Organización y Conducción de Obras', 4, 5, 2, 'ACTIVA'),
('Geotecnia Aplicada', 4, 5, 2, 'ACTIVA'),
('Proyecto Final', 4, 5, 2, 'ACTIVA'),

-- Area 5: Ingeniería Mecánica
('Análisis Matemático I', 5, 1, 1, 'ACTIVA'),
('Álgebra', 5, 1, 1, 'ACTIVA'),
('Sistemas de Representación', 5, 1, 1, 'ACTIVA'),
('Física I', 5, 1, 2, 'ACTIVA'),
('Química General', 5, 1, 2, 'ACTIVA'),
('Estabilidad I', 5, 1, 2, 'ACTIVA'),
('Análisis Matemático II', 5, 2, 1, 'ACTIVA'),
('Física II', 5, 2, 1, 'ACTIVA'),
('Conocimiento de Materiales', 5, 2, 2, 'ACTIVA'),
('Estabilidad II', 5, 3, 1, 'ACTIVA'),
('Mecanismos', 5, 3, 1, 'ACTIVA'),
('Mecánica de Fluidos', 5, 3, 2, 'ACTIVA'),
('Termodinámica', 5, 3, 2, 'ACTIVA'),
('Elementos de Máquinas', 5, 4, 1, 'ACTIVA'),
('Tecnología de Fabricación', 5, 4, 1, 'ACTIVA'),
('Máquinas Térmicas', 5, 4, 2, 'ACTIVA'),
('Instalaciones Industriales', 5, 4, 2, 'ACTIVA'),
('Mantenimiento Industrial', 5, 5, 1, 'ACTIVA'),
('Automación Industrial', 5, 5, 1, 'ACTIVA'),
('Organización Industrial', 5, 5, 2, 'ACTIVA'),
('Proyecto Final', 5, 5, 2, 'ACTIVA'),

-- Area 6: Licenciatura en Administración Rural
('Matemática', 6, 1, 1, 'ACTIVA'),
('Contabilidad General', 6, 1, 1, 'ACTIVA'),
('Introducción a la Producción Agropecuaria', 6, 1, 2, 'ACTIVA'),
('Economía I', 6, 1, 2, 'ACTIVA'),
('Administración General', 6, 2, 1, 'ACTIVA'),
('Estadística', 6, 2, 1, 'ACTIVA'),
('Producción Vegetal', 6, 2, 2, 'ACTIVA'),
('Producción Animal', 6, 2, 2, 'ACTIVA'),
('Administración Financiera', 6, 3, 1, 'ACTIVA'),
('Comercialización Agropecuaria', 6, 3, 1, 'ACTIVA'),
('Costos', 6, 3, 2, 'ACTIVA'),
('Legislación Rural', 6, 4, 1, 'ACTIVA'),
('Política Agropecuaria', 6, 4, 1, 'ACTIVA'),
('Planeamiento Agrario', 6, 4, 2, 'ACTIVA'),
('Seminario de Práctica Profesional', 6, 4, 2, 'ACTIVA'),

-- Area 7: Licenciatura en Tecnología Educativa
('Tecnología Educativa', 7, 1, 1, 'ACTIVA'),
('Diseño Curricular y Tecnología', 7, 1, 1, 'ACTIVA'),
('Investigación Educativa', 7, 1, 2, 'ACTIVA'),
('Informática Educativa', 7, 1, 2, 'ACTIVA'),
('Producción de Materiales Didácticos', 7, 2, 1, 'ACTIVA'),
('Gestión de Proyectos Educativos', 7, 2, 2, 'ACTIVA'),
('Tesina Final', 7, 2, 2, 'ACTIVA'),

-- Area 8: Tecnicatura en Programación
('Matemática', 8, 1, 1, 'ACTIVA'),
('Sistema de Procesamiento de Datos', 8, 1, 1, 'ACTIVA'),
('Programación I', 8, 1, 1, 'ACTIVA'),
('Laboratorio de Computación I', 8, 1, 1, 'ACTIVA'),
('Inglés I', 8, 1, 2, 'ACTIVA'),
('Programación II', 8, 1, 2, 'ACTIVA'),
('Laboratorio de Computación II', 8, 1, 2, 'ACTIVA'),
('Arquitectura y Sistemas Operativos', 8, 1, 2, 'ACTIVA'),
('Inglés II', 8, 2, 1, 'ACTIVA'),
('Programación III', 8, 2, 1, 'ACTIVA'),
('Laboratorio de Computación III', 8, 2, 1, 'ACTIVA'),
('Estadística', 8, 2, 1, 'ACTIVA'),
('Laboratorio de Computación IV', 8, 2, 2, 'ACTIVA'),
('Diseño y Administración de Bases de Datos', 8, 2, 2, 'ACTIVA'),
('Organización Empresarial', 8, 2, 2, 'ACTIVA'),
('Metodología de Sistemas', 8, 2, 2, 'ACTIVA'),

-- Area 9: Tecnicatura en Mecatrónica
('Matemática', 9, 1, 1, 'ACTIVA'),
('Informática', 9, 1, 1, 'ACTIVA'),
('Electrotecnia', 9, 1, 1, 'ACTIVA'),
('Física', 9, 1, 2, 'ACTIVA'),
('Dibujo Tecnológico', 9, 1, 2, 'ACTIVA'),
('Química General', 9, 1, 2, 'ACTIVA'),
('Mecánica', 9, 2, 1, 'ACTIVA'),
('Electrónica', 9, 2, 1, 'ACTIVA'),
('Sistemas Mecatrónicos', 9, 2, 2, 'ACTIVA'),
('Automatización Industrial', 9, 2, 2, 'ACTIVA'),
('Control Numérico por Computadora', 9, 3, 1, 'ACTIVA'),
('Hidráulica y Neumática', 9, 3, 2, 'ACTIVA'),

-- Area 10: Tecnicatura en Logística
('Introducción a la Logística', 10, 1, 1, 'ACTIVA'),
('Matemática', 10, 1, 1, 'ACTIVA'),
('Contabilidad', 10, 1, 2, 'ACTIVA'),
('Gestión de Almacenes', 10, 1, 2, 'ACTIVA'),
('Canales de Distribución', 10, 1, 2, 'ACTIVA'),
('Gestión de Inventarios', 10, 2, 1, 'ACTIVA'),
('Transporte', 10, 2, 1, 'ACTIVA'),
('Costos Logísticos', 10, 2, 1, 'ACTIVA'),
('Comercio Exterior', 10, 2, 2, 'ACTIVA'),
('Sistemas de Información Logística', 10, 2, 2, 'ACTIVA'),

-- Area 11: Tecnicatura en Negociación de Bienes
('Derecho Civil y Comercial', 11, 1, 1, 'ACTIVA'),
('Tasaciones', 11, 1, 1, 'ACTIVA'),
('Corretaje Público', 11, 1, 2, 'ACTIVA'),
('Técnicas de Negociación', 11, 1, 2, 'ACTIVA'),
('Marketing', 11, 2, 1, 'ACTIVA'),
('Contabilidad y Elementos Financieros', 11, 2, 1, 'ACTIVA'),
('Práctica Profesional de Martillero', 11, 2, 2, 'ACTIVA'),

-- Area 12: Tecnicatura en Material Rodante Ferroviario
('Introducción al Transporte Ferroviario', 12, 1, 1, 'ACTIVA'),
('Matemática', 12, 1, 1, 'ACTIVA'),
('Física', 12, 1, 2, 'ACTIVA'),
('Material Rodante', 12, 2, 1, 'ACTIVA'),
('Sistemas de Freno', 12, 2, 1, 'ACTIVA'),
('Sistemas de Señalización', 12, 2, 2, 'ACTIVA'),
('Mantenimiento Ferroviario', 12, 3, 1, 'ACTIVA'),
('Seguridad Operativa', 12, 3, 2, 'ACTIVA');
