spring.application.name=atr
server.port=8092

# Configuración de la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=chiara
spring.datasource.password=0801
spring.datasource.url=jdbc:mysql://localhost:3306/db_atr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Esto actualizará automáticamente la base de datos según las entidades
spring.jpa.hibernate.ddl-auto=update
# Esto mostrará las consultas SQL en la consola para depuración
spring.jpa.show-sql=true

# Configuración de rutas
path_cross=http://localhost:5173
path_mapping=api/v1